# Generated by Django 4.2.3 on 2023-09-11 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume_app', '0003_alter_resume_photo'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReservEmail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reservemail', models.EmailField(max_length=254)),
            ],
        ),
    ]
